FixMakes <- function(test)
{
  test$VEHICLE_MAKE[test$VEHICLE_MAKE=="LANDROVER"] <- "LAND ROVER"
  test$VEHICLE_MAKE[test$VEHICLE_MAKE=="NISSAN DIESEL"] <- "NISSAN"
  test
}

FixMakeModel <- function(make, model,models,data,repl=FALSE)
{
  #first pass
  n_make <- grep (make ,data$VEHICLE_MAKE)
  n_model <-intersect(grep (models,data$VEHICLE_MODEL),n_make)
  na_submodel <- which(is.na(data$VEHICLE_SUB_MODEL))
  i <-intersect(n_model,na_submodel)
  data$VEHICLE_SUB_MODEL[i] <- data$VEHICLE_MODEL[i]
  data$VEHICLE_MODEL[i] <- model
  data$VEHICLE_SUB_MODEL[i]<-gsub(models,"",data$VEHICLE_SUB_MODEL[i])
  data$VEHICLE_SUB_MODEL[i] <- ltrim(data$VEHICLE_SUB_MODEL[i])
  
  #second pass
  j <- setdiff(n_model,i)
  data$VEHICLE_MODEL[j] <- model
  
  #replacement pass
  if(repl==TRUE)
  {
    data$VEHICLE_SUB_MODEL[n_model] <- paste(models,data$VEHICLE_SUB_MODEL[n_model])
    data$VEHICLE_SUB_MODEL[n_model] <- ltrim(gsub(model,"",data$VEHICLE_SUB_MODEL[n_model]))
    data$VEHICLE_MODEL[n_model] <- model
  }

  data
}





FixToyota <- function(test)
{
test <- FixMakeModel("TOYOTA","COROLLA","C[AO]?[CR]R?O?O?L?L?L?LI?A?",test)
test <- FixMakeModel("TOYOTA","HILUX","[LH][IU]L?(GH)?.?[HLK][UIYX][UXS]",test)
test <- FixMakeModel("TOYOTA","HIACE","HI.?ACE",test)
test <- FixMakeModel("TOYOTA","LITEACE","(LITE?)|(LIGHT.?ACE)",test)
test <- FixMakeModel("TOYOTA","TOWNACE","TOWN.?ACE",test)
test <- FixMakeModel("TOYOTA","MASTERACE","MASTER.?ACE",test)
test <- FixMakeModel("TOYOTA","TOYOACE","TOY.?ACE",test)
test <- FixMakeModel("TOYOTA","LANDCRUISER","(L/C)|((LAND|LAN|L).?C.*R.*R)",test)
test <- FixMakeModel("TOYOTA","CAMRY","CAMRY",test)
test <- FixMakeModel("TOYOTA","CORONA","CORONA",test)
test <- FixMakeModel("TOYOTA","CARINA","CARINA",test)
test <- FixMakeModel("TOYOTA","CORSA","CORSA",test)
test <- FixMakeModel("TOYOTA","STARLET","STARLET",test)
test <- FixMakeModel("TOYOTA","MR2","MR2",test)
test <- FixMakeModel("TOYOTA","PRIUS","PRIUS",test)
test <- FixMakeModel("TOYOTA","SUPRA","SUPRA",test)
test <- FixMakeModel("TOYOTA","CELICA","CELICA",test)
test <- FixMakeModel("TOYOTA","CRESSIDA","CRESS?I?[DN]A",test)
test <- FixMakeModel("TOYOTA","SPRINTER","SPRINTER",test)
test <- FixMakeModel("TOYOTA","PREVIA","PREVIA",test)
test <- FixMakeModel("TOYOTA","CRESTA","CRESTA",test)
test <- FixMakeModel("TOYOTA","CORONA","CORONA",test)
test <- FixMakeModel("TOYOTA","LEVIN","LEVIN",test)
test <- FixMakeModel("TOYOTA","LEXUS","LEXUS",test)
test <- FixMakeModel("TOYOTA","DYNA","DYNA",test)
test <- FixMakeModel("TOYOTA","CROWN","CROWN",test)
test <- FixMakeModel("TOYOTA","SOARER","SOARER",test)
test <- FixMakeModel("TOYOTA","BLIZZARD","BLIZZ?ARD",test)
test <- FixMakeModel("TOYOTA","TRUENO","TR[UV].?NO",test)
test <- FixMakeModel("TOYOTA","4RUNNER","(FOUR)|4.?RUNNER",test)
test <- FixMakeModel("TOYOTA","COASTER","COASTER",test)
test <- FixMakeModel("TOYOTA","CARIB","CARIB",test)
test <- FixMakeModel("TOYOTA","CIELO","CIELO",test)
test <- FixMakeModel("TOYOTA","CELICA","CELICI?A",test)
test <- FixMakeModel("TOYOTA","RAV4","RAV.?4",test)
test <- FixMakeModel("TOYOTA","MARK II","M.?.?K.?[TWO|2|1|I][1I]?",test)
test <- FixMakeModel("TOYOTA","HILUX","SR5",test,TRUE)
test <- FixMakeModel("TOYOTA","HILUX","SURF",test,TRUE)
test <- FixMakeModel("TOYOTA","LANDCRUISER","PRADO",test,TRUE)
test <- FixMakeModel("TOYOTA","5FD","5FD",test)
test <- FixMakeModel("TOYOTA","5FG","5FG",test)
test <- FixMakeModel("TOYOTA","6FD","6FD",test)
test <- FixMakeModel("TOYOTA","6FG","6FG",test)
test <- FixMakeModel("TOYOTA","7FD","7FD",test)
test <- FixMakeModel("TOYOTA","7FG","7FG",test)
test <- FixMakeModel("TOYOTA","8FD","8FD",test)
test <- FixMakeModel("TOYOTA","8FG","8FG",test)

test
}

FixAstonMartin <- function(test)
{
  test <- FixMakeModel("ASTON MARTIN","VANTAGE","VANTAGE",test)
  test <- FixMakeModel("ASTON MARTIN","VANQUISH","VANQUISH",test)
  test <- FixMakeModel("ASTON MARTIN","VOLANTE","VOLANTE",test)
  test <- FixMakeModel("ASTON MARTIN","DB2","DB.?2",test)
  test <- FixMakeModel("ASTON MARTIN","DB4","DB.?4",test)
  test <- FixMakeModel("ASTON MARTIN","DB5","DB.?5",test)
  test <- FixMakeModel("ASTON MARTIN","DB6","D.?B.?6",test)
  test <- FixMakeModel("ASTON MARTIN","DB7","DB.?7",test)
  test <- FixMakeModel("ASTON MARTIN","DB8","DB.?8",test)
  test <- FixMakeModel("ASTON MARTIN","DB9","DB.?9",test)
  test <- FixMakeModel("ASTON MARTIN","DBS","[E|D]BS",test)
  
  test
}

FixFord <- function(test)
{
  test <- FixMakeModel("FORD","COUPE","COUPE",test)
  test <- FixMakeModel("FORD","300Z","300Z",test)
  test <- FixMakeModel("FORD","TAURUS","TAURUS",test)
  test <- FixMakeModel("FORD","GALAXIE","GALAXIE",test)
  test <- FixMakeModel("FORD","ZODIAC","ZODIAC",test)
  test <- FixMakeModel("FORD","V8","^V8",test)
  test <- FixMakeModel("FORD","THUNDERBIRD","THUNDERBIRD",test)
  test <- FixMakeModel("FORD","F100","F100",test)
  test <- FixMakeModel("FORD","EVEREST","EVEREST",test)
  test <- FixMakeModel("FORD","F150","F150",test)
  test <- FixMakeModel("FORD","MODEL A","MODEL A",test)
  test <- FixMakeModel("FORD","LITEACE","LITEACE",test)
  test <- FixMakeModel("FORD","ANGLIA","ANGLIA",test)
  test <- FixMakeModel("FORD","ECOSPORT","ECOSPORT",test)
  test <- FixMakeModel("FORD","CAPRI","CAPRI",test)
  test <- FixMakeModel("FORD","ZEPHYR","ZEPHYR",test)
  test <- FixMakeModel("FORD","KA","^KA",test)
  test <- FixMakeModel("FORD","FAIRLANE","FAIRLANE",test)
  test <- FixMakeModel("FORD","ECONOVAN","ECONOVAN",test)
  test <- FixMakeModel("FORD","CORTINA","CORTINA",test)
  test <- FixMakeModel("FORD","TELSTAR","TELSTAR",test)
  test <- FixMakeModel("FORD","FESTIVA","FESTIVA",test)
  test <- FixMakeModel("FORD","FAIRMONT","FAIRMONT",test)
  test <- FixMakeModel("FORD","ESCORT","ESCORT",test)
  test <- FixMakeModel("FORD","EXPLORER","EXPLORER",test)
  test <- FixMakeModel("FORD","ESCAPE","ESCAPE",test)
  test <- FixMakeModel("FORD","KUGA","KUGA",test)
  test <- FixMakeModel("FORD","FALCON UTE","FALCON UTE",test)
  test <- FixMakeModel("FORD","MUSTANG","MUSTANG",test)
  test <- FixMakeModel("FORD","LASER","LASER",test)
  test <- FixMakeModel("FORD","FIESTA","FIESTA",test)
  test <- FixMakeModel("FORD","TRANSIT","TRANSIT",test)
  test <- FixMakeModel("FORD","TERRITORY","TERRITORY",test)
  test <- FixMakeModel("FORD","COURIER","COURIER",test)
  test <- FixMakeModel("FORD","FOCUS","FOCUS",test)
  test <- FixMakeModel("FORD","MONDEO","MONDEO",test)
  test <- FixMakeModel("FORD","RANGER","RANGER",test)
  test <- FixMakeModel("FORD","FALCON","FALCON",test)  
  
  test
}

FixNissan <- function(test)
{
  test <- FixMakeModel("NISSAN", "SENTRA","(SENTRA)|(SENTRE)|(SENTR )|(SENT.?A)",test)
  test <- FixMakeModel("NISSAN", "PULSAR","PULS[AE]R?",test)
  test <- FixMakeModel("NISSAN", "GTR","GT.?R",test)
  test <- FixMakeModel("NISSAN", "PRIMERA","PRIMERA",test)
  test <- FixMakeModel("NISSAN", "PRESEA","PRESS?E?A\\b",test)
  test <- FixMakeModel("NISSAN", "SKYLINE","SK?Y?.?LINE",test)
  test <- FixMakeModel("NISSAN", "SAFARI","SA[RF]F?A?R[IO]",test)
  test <- FixMakeModel("NISSAN", "PATHFINDER","PATH.?FINDER",test)
  test <- FixMakeModel("NISSAN", "LUCINO","(LUCINO)|(ATT?ESS?A)",test)
  test <- FixMakeModel("NISSAN", "SUNNY","SUNNY",test)
  test <- FixMakeModel("NISSAN", "TERRANO","TERR?A?NO",test)
  test <- FixMakeModel("NISSAN", "SILVIA","(S[IY]LVI[AO])|(SIL?.?V.?A)",test)
  test <- FixMakeModel("NISSAN", "BLUEBIRD","(BLU.?.?B[IR][RI].*D)|(BLUE BI)|(WIDETR)|(BLUEBIRD)|(B.?BIRD)",test)
  test <- FixMakeModel("NISSAN", "SCORPION","SCORPION",test)
  test <- FixMakeModel("NISSAN", "PATROL","PA[RT][RT]OL",test)
  test <- FixMakeModel("NISSAN", "PICK UP","PICK.?UP",test)
  test <- FixMakeModel("NISSAN", "NAVARA","([MH]AVARA)|(NAVA.?.?A?)|(N.?V.?.?RA)|(NAVAR[OAU])|(NA.?.?.?R.?A)",test)
  test <- FixMakeModel("NISSAN", "KINGCAB","KINGCAB",test)
  test <- FixMakeModel("NISSAN", "ATLAS","(ATLAS)|(ALIAS)",test)
  test <- FixMakeModel("NISSAN", "AVENIR","AVENIR",test)
  test <- FixMakeModel("NISSAN", "AD","(^AD$)|(^AD\ )|(^AD.?MAX)|(^AD21)",test)
  test <- FixMakeModel("NISSAN", "LAUREL","LAUR[AE]E?L",test)
  test <- FixMakeModel("NISSAN", "FAIRLADY","FAIR?.?LADY",test)
  test <- FixMakeModel("NISSAN", "VANETTE","VANN?ETT[EA]",test)
  test <- FixMakeModel("NISSAN", "MAXIMA","[NM]AXIMA",test)
  test <- FixMakeModel("NISSAN", "PRAIRIE","PRAIRI?E",test)
  test <- FixMakeModel("NISSAN", "GAZELLE","GAZZ?ELLE",test)
  test <- FixMakeModel("NISSAN", "GLORIA","GLORIA",test)
  test <- FixMakeModel("NISSAN", "CEFIRO","C[IE]FIRO",test)
  test <- FixMakeModel("NISSAN", "CEDRIC","CEDRIC",test)
  test <- FixMakeModel("NISSAN", "CARAVAN","CARA?VAN",test)
  test <- FixMakeModel("NISSAN", "CALIFORNIA","CALIFORNIA",test)
  test <- FixMakeModel("NISSAN", "CABALL","CABALL",test)
  test <- FixMakeModel("NISSAN", "CIVILIAN","(CILL.*V.*AN)|([CG]IVILL?I?AN)",test)
  test <- FixMakeModel("NISSAN", "HOMY","(HOME?Y)|(HO.?.?Y)",test)
  test <- FixMakeModel("NISSAN", "CONDOR","CONDO[NR]",test)
  test <- FixMakeModel("NISSAN", "LARGO","LARGO",test)
  test <- FixMakeModel("NISSAN", "INFINITI","INFINIT[IY]",test)
  test <- FixMakeModel("NISSAN", "NX","N[XZ].?[CR]",test)
  test <- FixMakeModel("NISSAN", "180B","^180B",test)
  test <- FixMakeModel("NISSAN", "180SX","^180[SZ]X",test)
  test <- FixMakeModel("NISSAN", "300Z","(300)|(^300Z)|(^ZX)",test)
  test <- FixMakeModel("NISSAN", "S CARGO","E?S.?.?G?CARGO",test)
  test <- FixMakeModel("NISSAN", "SPORTSWAGON","SPORTS?.?WAGON",test)
  test <- FixMakeModel("NISSAN", "CP200","CP.?200",test)
  test <- FixMakeModel("NISSAN", "CP180","CP.?180",test)
  test <- FixMakeModel("NISSAN", "CP210","CP.?210",test)
  test <- FixMakeModel("NISSAN", "CPB","CPB",test)
  test <- FixMakeModel("NISSAN", "CMB86","CMB.?86",test)
  test <- FixMakeModel("NISSAN", "CWA31","CWA31",test)
  test <- FixMakeModel("NISSAN", "CWA45","CWA4[5S]",test)
  test <- FixMakeModel("NISSAN", "CWA300","CWA?300",test)
  test <- FixMakeModel("NISSAN", "CWA330","CWA?330",test)
  test <- FixMakeModel("NISSAN", "CWA340","CWA?340",test)
  test <- FixMakeModel("NISSAN", "CGA340","CGA.*340",test)
  test <- FixMakeModel("NISSAN", "CWA380","CWA?380",test)
  test <- FixMakeModel("NISSAN", "C20","^C20",test)
  test <- FixMakeModel("NISSAN", "720","^720",test)
  test <- FixMakeModel("NISSAN", "P1F","P1F[12Z]",test)
  test <- FixMakeModel("NISSAN", "PJ01","PJ0[I1]",test)
  test <- FixMakeModel("NISSAN", "PJ02","PJ[O0]2",test)
  test <- FixMakeModel("NISSAN", "PH01","PH01",test)
  test <- FixMakeModel("NISSAN", "PH02","PH02",test)
  test <- FixMakeModel("NISSAN", "PG720","PG.?720",test)
  test <- FixMakeModel("NISSAN", "FJ02","F.?J02",test)
  test <- FixMakeModel("NISSAN", "FDG","FDG",test)
  test <- FixMakeModel("NISSAN", "F01","FJ?[O0]1",test)
  test <- FixMakeModel("NISSAN", "F02","FJ?[O0]2",test)
  test <- FixMakeModel("NISSAN", "F03","F03",test)
  test <- FixMakeModel("NISSAN", "F04","F04",test)
  test <- FixMakeModel("NISSAN", "FG","FG[DJ]",test)
  test <- FixMakeModel("NISSAN", "K1B1","K[L1]B1",test)
  test <- FixMakeModel("NISSAN", "UG02","UG[JLT][O0]2",test)
  test <- FixMakeModel("NISSAN", "UL02","UL[O0][2Z]",test)
  test <- FixMakeModel("NISSAN", "UG1","UG[1JL]",test)
  test <- FixMakeModel("NISSAN", "F04","F04",test)
  test <- FixMakeModel("NISSAN", "PL01","PL[0O]1",test)
  test <- FixMakeModel("NISSAN", "PL02","PL[0O][2Z]",test)
  test <- FixMakeModel("NISSAN", "KING CAB","KING.?[CK]",test)
  test <- FixMakeModel("NISSAN", "LANGLEY","L[OA]NG[RL]EY",test)
  test <- FixMakeModel("NISSAN", "LIBERTY","LIBERT[YA]",test)
  test <- FixMakeModel("NISSAN", "280Z","280.?[Z2]X?",test)
  test <- FixMakeModel("NISSAN", "300Z","300.?[Z2]X?",test)
  test <- FixMakeModel("NISSAN", "CL180","CL.?180",test)
  test <- FixMakeModel("NISSAN", "CM180","CM.?180",test)
  test <- FixMakeModel("NISSAN", "CM80","CM.?80",test)
  test <- FixMakeModel("NISSAN", "CM81","CM81",test)
  test <- FixMakeModel("NISSAN", "CM85","CM85",test)
  test <- FixMakeModel("NISSAN", "CM86","CM86",test)
  test <- FixMakeModel("NISSAN", "CM87","CM87",test)
  test <- FixMakeModel("NISSAN", "CM88","CM88",test)
  test <- FixMakeModel("NISSAN", "YG1F","YG1F",test)
  test <- FixMakeModel("NISSAN", "YGJ02","YG?J[O0]2",test)
  test <- FixMakeModel("NISSAN", "YGL02","YG?L[O0]2",test)
  test <- FixMakeModel("NISSAN", "NJ01","NJ[O0]1",test)
  test <- FixMakeModel("NISSAN", "NJ02","NJ[O0]2",test)
  
  test
}

FixHonda <- function(test)
{
test <- FixMakeModel("HONDA", "CIVIC","CIVIC",test)
test <- FixMakeModel("HONDA", "ODYSSEY","ODYSSEY",test)
test <- FixMakeModel("HONDA", "ACCORD","ACCORD",test)
test <- FixMakeModel("HONDA", "CRV","CRV",test)
test <- FixMakeModel("HONDA", "FIT","FIT",test)
test <- FixMakeModel("HONDA", "INTEGRA","INTEGRA",test)
test <- FixMakeModel("HONDA", "STREAM","STREAM",test)
test <- FixMakeModel("HONDA", "JAZZ","JAZZ",test)
test <- FixMakeModel("HONDA", "LOGO","LOGO",test)
test <- FixMakeModel("HONDA", "PRELUDE","PRELUDE",test)
test <- FixMakeModel("HONDA", "TORNEO","TORNEO",test)
test <- FixMakeModel("HONDA", "ORTHIA","ORTHIA",test)
test <- FixMakeModel("HONDA", "ASCOT","ASCOT",test)
test <- FixMakeModel("HONDA", "INSPIRE","INSPIRE",test)
test <- FixMakeModel("HONDA", "CONCERTO","CONCERTO",test)
test <- FixMakeModel("HONDA", "DOMANI","DOMANI",test)
test <- FixMakeModel("HONDA", "LEGEND","LEGEND",test)
test <- FixMakeModel("HONDA", "EDIX","EDIX",test)
test <- FixMakeModel("HONDA", "CITY","CITY",test)
test <- FixMakeModel("HONDA", "AIRWAVE","AIRWAVE",test)
test <- FixMakeModel("HONDA", "RAFAGA","RAFAGA",test)
test <- FixMakeModel("HONDA", "AVANCIER","AVANCIER",test)
test <- FixMakeModel("HONDA", "HR-V","HR.?V",test)
test <- FixMakeModel("HONDA", "STEPWAGON","STEPWAGON",test)
test <- FixMakeModel("HONDA", "ELYSION","ELYSION",test)
test <- FixMakeModel("HONDA", "INSIGHT","INSIGHT",test)
test <- FixMakeModel("HONDA", "NVS","NVS",test)
test <- FixMakeModel("HONDA", "CRX","CRX",test)
test <- FixMakeModel("HONDA", "CBR1000","CBR ?1000",test)
test <- FixMakeModel("HONDA", "CB500","CB ?500",test)
test <- FixMakeModel("HONDA", "CB650","CB ?650",test)
test <- FixMakeModel("HONDA", "CG125","CG ?125",test)
test <- FixMakeModel("HONDA", "XL250","XL ?250",test)
test <- FixMakeModel("HONDA", "XL650","XL ?650",test)
test <- FixMakeModel("HONDA", "XL1000","XL ?1000",test)
test <- FixMakeModel("HONDA", "XL125","XL ?125",test)
test <- FixMakeModel("HONDA", "XL600","XL ?600",test)
test <- FixMakeModel("HONDA", "XL200","XL ?200",test)
test <- FixMakeModel("HONDA", "XL500","XL ?500",test)
test <- FixMakeModel("HONDA", "XL185","XL ?185",test)
test <- FixMakeModel("HONDA", "XL350","XL ?350",test)
test <- FixMakeModel("HONDA", "CX500","CX ?500",test)
test <- FixMakeModel("HONDA", "CB250","CB ?250",test)
test <- FixMakeModel("HONDA", "XR125","XR ?125",test)
test <- FixMakeModel("HONDA", "XR185","XR ?185",test)
test <- FixMakeModel("HONDA", "XR200","XR ?200",test)
test <- FixMakeModel("HONDA", "XR250","XR ?250",test)
test <- FixMakeModel("HONDA", "XR400","XR ?400",test)
test <- FixMakeModel("HONDA", "XR500","XR ?500",test)
test <- FixMakeModel("HONDA", "TRX500","TRX ?500",test)
test <- FixMakeModel("HONDA", "CB750","CB ?750",test)
test <- FixMakeModel("HONDA", "CB900","CB ?900",test)
test <- FixMakeModel("HONDA", "CB400","CB ?400",test)
test <- FixMakeModel("HONDA", "CB550","CB ?550",test)
test <- FixMakeModel("HONDA", "GL1200","GL ?1200",test)

test
}


FixHolden <- function(test)
{
test <- FixMakeModel("HOLDEN","ZAFIRA","ZAFIRA",test)
test <- FixMakeModel("HOLDEN","SS","^SS$",test)
test <- FixMakeModel("HOLDEN","SUNBIRD","SUNBIRD",test)
test <- FixMakeModel("HOLDEN","EH","( EH)|(EH )",test)
test <- FixMakeModel("HOLDEN","EJ","( EJ)|(EJ )",test)
test <- FixMakeModel("HOLDEN","WH","( WH)|(WH )",test)
test <- FixMakeModel("HOLDEN","HQ","( HQ)|(HQ )",test)
test <- FixMakeModel("HOLDEN","HK","( HK)|(HK )",test)
test <- FixMakeModel("HOLDEN","HJ","( HJ)|(HJ )",test)
test <- FixMakeModel("HOLDEN","FJ","( FJ)|(FJ )",test)
test <- FixMakeModel("HOLDEN","COMMODORE","EXECUTIVE",test)
test <- FixMakeModel("HOLDEN","SPECIAL","SPECIAL",test)
test <- FixMakeModel("HOLDEN","COROLLA","COROLLA",test)
test <- FixMakeModel("HOLDEN","BELMONT","BELMONT",test)
test <- FixMakeModel("HOLDEN","SPARK","SPARK",test)
test <- FixMakeModel("HOLDEN","COMBO","COMBO",test)
test <- FixMakeModel("HOLDEN","STATESMAN","ST?ATESMAN",test)
test <- FixMakeModel("HOLDEN","TORANA","TOR[OA]N?[OA]",test)
test <- FixMakeModel("HOLDEN","PREMIER","PREMIER",test)
test <- FixMakeModel("HOLDEN","VT","^VT$",test)
test <- FixMakeModel("HOLDEN","MALIBU","MALIBU",test)
test <- FixMakeModel("HOLDEN","CALAIS","CALAIS",test)
test <- FixMakeModel("HOLDEN","BERLINA","BERLINA",test)
test <- FixMakeModel("HOLDEN","EPICA","EPICA",test)
test <- FixMakeModel("HOLDEN","MONARO","MONARO",test)
test <- FixMakeModel("HOLDEN","CREWMAN","CREWMAN",test)
test <- FixMakeModel("HOLDEN","VIVA","VIVA",test)
test <- FixMakeModel("HOLDEN","TRAX","TRAX",test)
test <- FixMakeModel("HOLDEN","KINGSWOOD","(KII?NGS?WOO*D)|(KWOOD)|(K/WOOD)|(^K/W)",test)
test <- FixMakeModel("HOLDEN","VECTRA","VECTRA",test)
test <- FixMakeModel("HOLDEN","RODEO","RODEO ",test)
test <- FixMakeModel("HOLDEN","ASTRA","ASTRA",test)
test <- FixMakeModel("HOLDEN","BARINA","BARINA",test)
test <- FixMakeModel("HOLDEN","CRUZE","CRUZE",test)
test <- FixMakeModel("HOLDEN","CAPTIVA","CAPTIVA",test)
test <- FixMakeModel("HOLDEN","ROYALE","ROYALE?",test)
test <- FixMakeModel("HOLDEN","SENATOR","SENATOR?",test)
test <- FixMakeModel("HOLDEN","COLORADO","COLORADO",test)
test <- FixMakeModel("HOLDEN","COMMODORE","(COMM)|(COMM[EOA]?R?DORE?)",test)
test <- FixMakeModel("HOLDEN","AVALANCHE","AVA[LI]ANCHE",test)

test
}

FixMazda <- function(test)
{
test <- FixMakeModel("MAZDA","CRONOS","CRONOS",test)
test <- FixMakeModel("MAZDA","RX3","RX.?3",test)
test <- FixMakeModel("MAZDA","121","121",test)
test <- FixMakeModel("MAZDA","COUPE","COUPE",test)
test <- FixMakeModel("MAZDA","ASTINA","ASTINA",test)
test <- FixMakeModel("MAZDA","B2200","B2200",test)
test <- FixMakeModel("MAZDA","REVUE","REVUE",test)
test <- FixMakeModel("MAZDA","RX8","RX.?8",test)
test <- FixMakeModel("MAZDA","B2000","B2000",test)
test <- FixMakeModel("MAZDA","MX5","MX.?5",test)
test <- FixMakeModel("MAZDA","B2600","B2600",test)
test <- FixMakeModel("MAZDA","B1600","B1600",test)
test <- FixMakeModel("MAZDA","E1800","E1800",test)
test <- FixMakeModel("MAZDA","AUTOZAM","AUTOZAM",test)
test <- FixMakeModel("MAZDA","MX5","MX.?5",test)
test <- FixMakeModel("MAZDA","RX7","RX.?7",test)
test <- FixMakeModel("MAZDA","B2500","B2500",test)
test <- FixMakeModel("MAZDA","E2000","E2000",test)
test <- FixMakeModel("MAZDA","CX9","CX.?9",test)
test <- FixMakeModel("MAZDA","ROADSTER","ROADSTER",test)
test <- FixMakeModel("MAZDA","PROCEED","PROCEED",test)
test <- FixMakeModel("MAZDA","RX8","RX.?8",test)
test <- FixMakeModel("MAZDA","CX3","CX.?3",test)
test <- FixMakeModel("MAZDA","LANTIS","LANTIS",test)
test <- FixMakeModel("MAZDA","EUNOS","EUNOS",test)
test <- FixMakeModel("MAZDA","TRIBUTE","TRIBUTE",test)
test <- FixMakeModel("MAZDA","TITAN","TITAN",test)
test <- FixMakeModel("MAZDA","CX7","CX.?7",test)
test <- FixMakeModel("MAZDA","VERISA","VERISA",test)
test <- FixMakeModel("MAZDA","BONGO","BONGO",test)
test <- FixMakeModel("MAZDA","323","323",test)
test <- FixMakeModel("MAZDA","626","626",test)
test <- FixMakeModel("MAZDA","929","929",test)
test <- FixMakeModel("MAZDA","CAPELLA","CAPELLA",test)
test <- FixMakeModel("MAZDA","BOUNTY","BOUNTY",test)
test <- FixMakeModel("MAZDA","PREMACY","PREMACY",test)
test <- FixMakeModel("MAZDA","MAZDA2","MAZDA2",test)
test <- FixMakeModel("MAZDA","CX5","CX5",test)
test <- FixMakeModel("MAZDA","BT-50","BT.?50",test)
test <- FixMakeModel("MAZDA","MPV","MPV",test)
test <- FixMakeModel("MAZDA","MAZDA6","(MAZDA.?6)|(^6$)",test)
test <- FixMakeModel("MAZDA","MAZDA3","(MAZDA.?3)|(^3$)",test)
test <- FixMakeModel("MAZDA","ATENZA","ATENZA",test)
test <- FixMakeModel("MAZDA","FAMILIA","FAMILIA",test)
test <- FixMakeModel("MAZDA","AXELA","AXELA",test)
test <- FixMakeModel("MAZDA","DEMIO","DEMIO",test)

test
}

FixMitsubishi <- function(test)
{
  test <- FixMakeModel("MITSUBISHI","FE091C CAMPER","FE091C CAMPER",test)
  test <- FixMakeModel("MITSUBISHI","STRADA","STRADA",test)
  test <- FixMakeModel("MITSUBISHI","EMERAUDE","EMERAUDE",test)
  test <- FixMakeModel("MITSUBISHI","CEDIA","CEDIA",test)
  test <- FixMakeModel("MITSUBISHI","NIMBUS","NIMBUS",test)
  test <- FixMakeModel("MITSUBISHI","ETERNA","ETERNA",test)
  test <- FixMakeModel("MITSUBISHI","SIGMA","SIGMA",test)
  test <- FixMakeModel("MITSUBISHI","I-CAR","I-CAR",test)
  test <- FixMakeModel("MITSUBISHI","LANDCRUISER","LANDCRUISER",test)
  test <- FixMakeModel("MITSUBISHI","CARISMA","CARISMA",test)
  test <- FixMakeModel("MITSUBISHI","ROSA","ROSA",test)
  test <- FixMakeModel("MITSUBISHI","MAGNA","MAGNA",test)
  test <- FixMakeModel("MITSUBISHI","DION","DION",test)
  test <- FixMakeModel("MITSUBISHI","GTO","GTO",test)
  test <- FixMakeModel("MITSUBISHI","SHOGUN","SHOGUN",test)
  test <- FixMakeModel("MITSUBISHI","FTO","FTO",test)
  test <- FixMakeModel("MITSUBISHI","LIBERO","LIBERO",test)
  test <- FixMakeModel("MITSUBISHI","380","380",test)
  test <- FixMakeModel("MITSUBISHI","FIGHTER","FIGHTER",test)
  test <- FixMakeModel("MITSUBISHI","GRANDIS","GRANDIS",test)
  test <- FixMakeModel("MITSUBISHI","FUSO","FUSO",test)
  test <- FixMakeModel("MITSUBISHI","AIRTREK","AIRTREK",test)
  test <- FixMakeModel("MITSUBISHI","CHALLENGER","CHALLENGER",test)
  test <- FixMakeModel("MITSUBISHI","CHARIOT","CHARIOT",test)
  test <- FixMakeModel("MITSUBISHI","DELICA","DELICA",test)
  test <- FixMakeModel("MITSUBISHI","ASX","ASX",test)
  test <- FixMakeModel("MITSUBISHI","LEGNUM","LEGNUM",test)
  test <- FixMakeModel("MITSUBISHI","RVR","RVR",test)
  test <- FixMakeModel("MITSUBISHI","L200","L200",test)
  test <- FixMakeModel("MITSUBISHI","CANTER","CANTER",test)
  test <- FixMakeModel("MITSUBISHI","DIAMANTE","DIAMANTE",test)
  test <- FixMakeModel("MITSUBISHI","MIRAGE","MIRAGE",test)
  test <- FixMakeModel("MITSUBISHI","COLT","COLT",test)
  test <- FixMakeModel("MITSUBISHI","GALANT","GALANT",test)
  test <- FixMakeModel("MITSUBISHI","300Z","300Z",test)
  test <- FixMakeModel("MITSUBISHI","PAJERO","PAJERO",test)
  test <- FixMakeModel("MITSUBISHI","TRITON","TRITON",test)
  test <- FixMakeModel("MITSUBISHI","OUTLANDER","OUTLANDER",test)
  test <- FixMakeModel("MITSUBISHI","LANCER","LANCER",test)

test
}


FixSuzuki <- function(test)
{
  test <- FixMakeModel("SUZUKI","VL1500","VL1500",test)
  test <- FixMakeModel("SUZUKI","GSF","GSF",test)
  test <- FixMakeModel("SUZUKI","300Z","300Z",test)
  test <- FixMakeModel("SUZUKI","GZ250","GZ250",test)
  test <- FixMakeModel("SUZUKI","CELERIO","CELERIO",test)
  test <- FixMakeModel("SUZUKI","DL650","DL650",test)
  test <- FixMakeModel("SUZUKI","GSX-R750","GSX-R750",test)
  test <- FixMakeModel("SUZUKI","GSXR","GSXR",test)
  test <- FixMakeModel("SUZUKI","GSF1250","GSF1250",test)
  test <- FixMakeModel("SUZUKI","GSX-R600","GSX-R600",test)
  test <- FixMakeModel("SUZUKI","SV1000","SV1000",test)
  test <- FixMakeModel("SUZUKI","VZR","VZR",test)
  test <- FixMakeModel("SUZUKI","WAGON R","WAGON R",test)
  test <- FixMakeModel("SUZUKI","DL1000","DL1000",test)
  test <- FixMakeModel("SUZUKI","GSF1200S","GSF1200S",test)
  test <- FixMakeModel("SUZUKI","VL800","VL800",test)
  test <- FixMakeModel("SUZUKI","SAMURAI","SAMURAI",test)
  test <- FixMakeModel("SUZUKI","SJ50","SJ50",test)
  test <- FixMakeModel("SUZUKI","VZ800","VZ800",test)
  test <- FixMakeModel("SUZUKI","GW250","GW250",test)
  test <- FixMakeModel("SUZUKI","DR-Z400","DR-Z400",test)
  test <- FixMakeModel("SUZUKI","WAGON R+","WAGON R+",test)
  test <- FixMakeModel("SUZUKI","LS650","LS650",test)
  test <- FixMakeModel("SUZUKI","GS","GS",test)
  test <- FixMakeModel("SUZUKI","UZ50","UZ50",test)
  test <- FixMakeModel("SUZUKI","SJ50QT","SJ50QT",test)
  test <- FixMakeModel("SUZUKI","IGNIS","IGNIS",test)
  test <- FixMakeModel("SUZUKI","AN125","AN125",test)
  test <- FixMakeModel("SUZUKI","VL250","VL250",test)
  test <- FixMakeModel("SUZUKI","CARRY","CARRY",test)
  test <- FixMakeModel("SUZUKI","DR650SE","DR650SE",test)
  test <- FixMakeModel("SUZUKI","APV","APV",test)
  test <- FixMakeModel("SUZUKI","GN125H","GN125H",test)
  test <- FixMakeModel("SUZUKI","LIANA","LIANA",test)
  test <- FixMakeModel("SUZUKI","KIZASHI","KIZASHI",test)
  test <- FixMakeModel("SUZUKI","SPLASH","SPLASH",test)
  test <- FixMakeModel("SUZUKI","GSX","GSX",test)
  test <- FixMakeModel("SUZUKI","BALENO","BALENO",test)
  test <- FixMakeModel("SUZUKI","GN250","GN250",test)
  test <- FixMakeModel("SUZUKI","AERIO","AERIO",test)
  test <- FixMakeModel("SUZUKI","CULTUS","CULTUS",test)
  test <- FixMakeModel("SUZUKI","JIMNY","JIMNY",test)
  test <- FixMakeModel("SUZUKI","ALTO","ALTO",test)
  test <- FixMakeModel("SUZUKI","VITARA","^VITARA",test)
  test <- FixMakeModel("SUZUKI","GRAND VITARA","GRAND VITARA",test)
  test <- FixMakeModel("SUZUKI","ESCUDO","ESCUDO",test)
  test <- FixMakeModel("SUZUKI","SX4","SX4",test)
  test <- FixMakeModel("SUZUKI","SWIFT","SWIFT",test)
  
  test
}


FixSubaru <- function(test)
{
test <- FixMakeModel("SUBARU","BIGHORN","BIGHORN",test)
test <- FixMakeModel("SUBARU","UTE","UTE",test)
test <- FixMakeModel("SUBARU","HALO","HALO",test)
test <- FixMakeModel("SUBARU","VORTEX","VORTEX",test)
test <- FixMakeModel("SUBARU","DOMINGO","DOMINGO",test)
test <- FixMakeModel("SUBARU","R2","R2",test)
test <- FixMakeModel("SUBARU","VIVIO","VIVIO",test)
test <- FixMakeModel("SUBARU","ALCYONE","ALCYONE",test)
test <- FixMakeModel("SUBARU","1800","1800",test)
test <- FixMakeModel("SUBARU","COUPE","COUPE",test)
test <- FixMakeModel("SUBARU","LANCASTER","LANCASTER",test)
test <- FixMakeModel("SUBARU","4WD","4WD",test)
test <- FixMakeModel("SUBARU","LIBERTY","LIBERTY",test)
test <- FixMakeModel("SUBARU","SAMBAR","SAMBAR",test)
test <- FixMakeModel("SUBARU","BRZ","BRZ",test)
test <- FixMakeModel("SUBARU","MPV","MPV",test)
test <- FixMakeModel("SUBARU","LEVORG","LEVORG",test)
test <- FixMakeModel("SUBARU","OMEGA","OMEGA",test)
test <- FixMakeModel("SUBARU","BRUMBY","BRUMBY",test)
test <- FixMakeModel("SUBARU","SVX","SVX",test)
test <- FixMakeModel("SUBARU","LEONE","LEONE",test)
test <- FixMakeModel("SUBARU","TRAVIQ","TRAVIQ",test)
test <- FixMakeModel("SUBARU","ACE","ACE",test)
test <- FixMakeModel("SUBARU","JUSTY","JUSTY",test)
test <- FixMakeModel("SUBARU","WRX","WRX",test)
test <- FixMakeModel("SUBARU","TRIBECA","TRIBECA",test)
test <- FixMakeModel("SUBARU","EXIGA","EXIGA",test)
test <- FixMakeModel("SUBARU","XV","XV",test)
test <- FixMakeModel("SUBARU","OUTBACK","OUTBACK",test)
test <- FixMakeModel("SUBARU","FORESTER","FORESTER",test)
test <- FixMakeModel("SUBARU","IMPREZA","IMPREZA",test)
test <- FixMakeModel("SUBARU","LEGACY","LEGACY",test)

test
}


FixVolkswagen <- function(test) {
  test <- FixMakeModel("VOLKSWAGEN","T4","T4",test)
  test <- FixMakeModel("VOLKSWAGEN","SUPER BEETLE","SUPER BEETLE",test)
  test <- FixMakeModel("VOLKSWAGEN","PHAETON","PHAETON",test)
  test <- FixMakeModel("VOLKSWAGEN","1303S","1303S",test)
  test <- FixMakeModel("VOLKSWAGEN","CROSSTOURAN","CROSSTOURAN",test)
  test <- FixMakeModel("VOLKSWAGEN","TRIKE","TRIKE",test)
  test <- FixMakeModel("VOLKSWAGEN","CAMPER","CAMPER",test)
  test <- FixMakeModel("VOLKSWAGEN","114","114",test)
  test <- FixMakeModel("VOLKSWAGEN","CALIFORNIA","CALIFORNIA",test)
  test <- FixMakeModel("VOLKSWAGEN","BEACH BUGGY","BEACH BUGGY",test)
  test <- FixMakeModel("VOLKSWAGEN","VENTO","VENTO",test)
  test <- FixMakeModel("VOLKSWAGEN","1600","1600",test)
  test <- FixMakeModel("VOLKSWAGEN","MICROBUS","MICROBUS",test)
  test <- FixMakeModel("VOLKSWAGEN","CARAVELLE","CARAVELLE",test)
  test <- FixMakeModel("VOLKSWAGEN","COMBI","COMBI",test)
  test <- FixMakeModel("VOLKSWAGEN","CROSSPOLO","CROSSPOLO",test)
  test <- FixMakeModel("VOLKSWAGEN","LUPO","LUPO",test)
  test <- FixMakeModel("VOLKSWAGEN","SHARAN","SHARAN",test)
  test <- FixMakeModel("VOLKSWAGEN","1302S","1302S",test)
  test <- FixMakeModel("VOLKSWAGEN","1200","1200",test)
  test <- FixMakeModel("VOLKSWAGEN","LT46","LT46",test)
  test <- FixMakeModel("VOLKSWAGEN","SCIROCCO","SCIROCCO",test)
  test <- FixMakeModel("VOLKSWAGEN","T6","T6",test)
  test <- FixMakeModel("VOLKSWAGEN","TRANSPORTER","TRANSPORTER",test)
  test <- FixMakeModel("VOLKSWAGEN","KOMBI","KOMBI",test)
  test <- FixMakeModel("VOLKSWAGEN","JETTA","JETTA",test)
  test <- FixMakeModel("VOLKSWAGEN","1500","1500",test)
  test <- FixMakeModel("VOLKSWAGEN","BORA","BORA",test)
  test <- FixMakeModel("VOLKSWAGEN","TOURAN","TOURAN",test)
  test <- FixMakeModel("VOLKSWAGEN","LT35","LT35",test)
  test <- FixMakeModel("VOLKSWAGEN","CROSS POLO","CROSS POLO",test)
  test <- FixMakeModel("VOLKSWAGEN","EOS","EOS",test)
  test <- FixMakeModel("VOLKSWAGEN","CADDY","CADDY",test)
  test <- FixMakeModel("VOLKSWAGEN","CRAFTER","CRAFTER",test)
  test <- FixMakeModel("VOLKSWAGEN","T5","T5",test)
  test <- FixMakeModel("VOLKSWAGEN","TOUAREG","TOUAREG",test)
  test <- FixMakeModel("VOLKSWAGEN","AMAROK","AMAROK",test)
  test <- FixMakeModel("VOLKSWAGEN","TIGUAN","TIGUAN",test)
  test <- FixMakeModel("VOLKSWAGEN","BEETLE","BEETLE",test)
  test <- FixMakeModel("VOLKSWAGEN","PASSAT","PASSAT",test)
  test <- FixMakeModel("VOLKSWAGEN","POLO","POLO",test)
  test <- FixMakeModel("VOLKSWAGEN","GOLF","GOLF",test)

  test
}

FixHyundai <- function(test) {
  test <- FixMakeModel("HYUNDAI","HL740-7","HL740-7",test)
  test <- FixMakeModel("HYUNDAI","R140W-9","R140W-9",test)
  test <- FixMakeModel("HYUNDAI","HD45","HD45",test)
  test <- FixMakeModel("HYUNDAI","HD65","HD65",test)
  test <- FixMakeModel("HYUNDAI","HD60","HD60",test)
  test <- FixMakeModel("HYUNDAI","FX","FX",test)
  test <- FixMakeModel("HYUNDAI","GENESIS","GENESIS",test)
  test <- FixMakeModel("HYUNDAI","EXCEL","EXCEL",test)
  test <- FixMakeModel("HYUNDAI","XG","XG",test)
  test <- FixMakeModel("HYUNDAI","JM","JM",test)
  test <- FixMakeModel("HYUNDAI","HD75","HD75",test)
  test <- FixMakeModel("HYUNDAI","GRANDEUR XG","GRANDEUR XG",test)
  test <- FixMakeModel("HYUNDAI","MATRIX","MATRIX",test)
  test <- FixMakeModel("HYUNDAI","ATOZ","ATOZ",test)
  test <- FixMakeModel("HYUNDAI","TIBURON","TIBURON",test)
  test <- FixMakeModel("HYUNDAI","TRAJET","TRAJET",test)
  test <- FixMakeModel("HYUNDAI","GRANDEUR","GRANDEUR",test)
  test <- FixMakeModel("HYUNDAI","LAVITA","LAVITA",test)
  test <- FixMakeModel("HYUNDAI","VELOSTER","VELOSTER",test)
  test <- FixMakeModel("HYUNDAI","COUPE","COUPE",test)
  test <- FixMakeModel("HYUNDAI","TERRACAN","TERRACAN",test)
  test <- FixMakeModel("HYUNDAI","IMAX","IMAX",test)
  test <- FixMakeModel("HYUNDAI","H100","H100",test)
  test <- FixMakeModel("HYUNDAI","I40","I40",test)
  test <- FixMakeModel("HYUNDAI","TB","TB",test)
  test <- FixMakeModel("HYUNDAI","I45","I45",test)
  test <- FixMakeModel("HYUNDAI","H1","H1",test)
  test <- FixMakeModel("HYUNDAI","ILOAD","ILOAD",test)
  test <- FixMakeModel("HYUNDAI","LANTRA","LANTRA",test)
  test <- FixMakeModel("HYUNDAI","I20","I20",test)
  test <- FixMakeModel("HYUNDAI","ELANTRA","ELANTRA",test)
  test <- FixMakeModel("HYUNDAI","SONATA","SONATA",test)
  test <- FixMakeModel("HYUNDAI","ACCENT","ACCENT",test)
  test <- FixMakeModel("HYUNDAI","GETZ","GETZ",test)
  test <- FixMakeModel("HYUNDAI","TUCSON","TUCSON",test)
  test <- FixMakeModel("HYUNDAI","IX35","IX35",test)
  test <- FixMakeModel("HYUNDAI","I30","I30",test)
  test <- FixMakeModel("HYUNDAI","SANTA FE","SANTA FE",test)
  
  test
}

FixIsuzu <- function(test) {
  test <- FixMakeModel("ISUZU","4X4 UTE","4X4 UTE",test)
  test <- FixMakeModel("ISUZU","JCS420","JCS420",test)
  test <- FixMakeModel("ISUZU","IRMSCHER","IRMSCHER",test)
  test <- FixMakeModel("ISUZU","KT26","^KT26",test)
  test <- FixMakeModel("ISUZU","NKR552","NKR552",test)
  test <- FixMakeModel("ISUZU","SBR422","SBR422",test)
  test <- FixMakeModel("ISUZU","EXY","^EXY",test)
  test <- FixMakeModel("ISUZU","KS32","^KS32",test)
  test <- FixMakeModel("ISUZU","NPS","^NPS",test)
  test <- FixMakeModel("ISUZU","NPR400","^NPR400",test)
  test <- FixMakeModel("ISUZU","TFR","TFR",test)
  test <- FixMakeModel("ISUZU","FASTER","FASTER",test)
  test <- FixMakeModel("ISUZU","FTS","^FTS",test)
  test <- FixMakeModel("ISUZU","GEMINI","GEMINI",test)
  test <- FixMakeModel("ISUZU","FSR","^FSR",test)
  test <- FixMakeModel("ISUZU","CYH","^CYH",test)
  test <- FixMakeModel("ISUZU","TROOPER","TROOPER",test)
  test <- FixMakeModel("ISUZU","FRR","^FRR",test)
  test <- FixMakeModel("ISUZU","FVR","^FVR",test)
  test <- FixMakeModel("ISUZU","COMO","COMO",test)
  test <- FixMakeModel("ISUZU","CYJ","^CYJ",test)
  test <- FixMakeModel("ISUZU","CYZ","^CYZ",test)
  test <- FixMakeModel("ISUZU","NQR","^NQR",test)
  test <- FixMakeModel("ISUZU","FTR","^FTR",test)
  test <- FixMakeModel("ISUZU","NKR","^NKR",test)
  test <- FixMakeModel("ISUZU","EXZ","^EXZ",test)
  test <- FixMakeModel("ISUZU","FARGO","FARGO",test)
  test <- FixMakeModel("ISUZU","C SERIES","C SERIES",test)
  test <- FixMakeModel("ISUZU","RODEO","RODEO",test)
  test <- FixMakeModel("ISUZU","CXZ","CXZ",test)
  test <- FixMakeModel("ISUZU","CXH","CXH",test)
  test <- FixMakeModel("ISUZU","GIGA","GIGA",test)
  test <- FixMakeModel("ISUZU","C&E SERIES","C&E SERIES",test)
  test <- FixMakeModel("ISUZU","FVZ","^FVZ",test)
  test <- FixMakeModel("ISUZU","JOURNEY","JOURNEY",test)
  test <- FixMakeModel("ISUZU","NPR","NPR",test)
  test <- FixMakeModel("ISUZU","WIZARD","WIZARD",test)
  test <- FixMakeModel("ISUZU","F SERIES","F SERIES",test)
  test <- FixMakeModel("ISUZU","FORWARD","FORWARD",test)
  test <- FixMakeModel("ISUZU","MU","MU",test)
  test <- FixMakeModel("ISUZU","N SERIES","N SERIES",test)
  test <- FixMakeModel("ISUZU","D-MAX","D-MAX",test)
  test <- FixMakeModel("ISUZU","ELF","ELF",test)
  test <- FixMakeModel("ISUZU","BIGHORN","BIGHORN",test)

  test
}

FixBmw <- function(test) {
  test <- FixMakeModel("BMW","745I","^745.?I",test)
  test <- FixMakeModel("BMW","316","^316",test)
  test <- FixMakeModel("BMW","735I","^735.?I",test)
  test <- FixMakeModel("BMW","730I","^730.?I",test)
  test <- FixMakeModel("BMW","330CI","^330.?CI",test)
  test <- FixMakeModel("BMW","M5","^M5",test)
  test <- FixMakeModel("BMW","550I","^550.?I",test)
  test <- FixMakeModel("BMW","316I","^316.?I",test)
  test <- FixMakeModel("BMW","R1100","^R1100",test)
  test <- FixMakeModel("BMW","130I","^130.?I",test)
  test <- FixMakeModel("BMW","523I","^523.?I",test)
  test <- FixMakeModel("BMW","530D","^530.?D",test)
  test <- FixMakeModel("BMW","118D","^118.?D",test)
  test <- FixMakeModel("BMW","1 SERIES","1 SERIES",test)
  test <- FixMakeModel("BMW","316TI","^316.?TI",test)
  test <- FixMakeModel("BMW","2 SERIES","2 SERIES",test)
  test <- FixMakeModel("BMW","740I","^740.?I",test)
  test <- FixMakeModel("BMW","3 SERIES","3 SERIES",test)
  test <- FixMakeModel("BMW","320","^320",test)
  test <- FixMakeModel("BMW","X1","^X1",test)
  test <- FixMakeModel("BMW","F650","^F650",test)
  test <- FixMakeModel("BMW","COMPACT","^COMPACT",test)
  test <- FixMakeModel("BMW","M3","^M3",test)
  test <- FixMakeModel("BMW","Z4","^Z4",test)
  test <- FixMakeModel("BMW","540I","^540.?I",test)
  test <- FixMakeModel("BMW","R1200","^R1200",test)
  test <- FixMakeModel("BMW","335I","^335.?I",test)
  test <- FixMakeModel("BMW","520I","^520.?I",test)
  test <- FixMakeModel("BMW","528I","^528.?I",test)
  test <- FixMakeModel("BMW","320D","^320.?D",test)
  test <- FixMakeModel("BMW","Z3","^Z3",test)
  test <- FixMakeModel("BMW","118I","^118.?I",test)
  test <- FixMakeModel("BMW","120I","^120.?I",test)
  test <- FixMakeModel("BMW","530I","^530.?I",test)
  test <- FixMakeModel("BMW","X3","^X3",test)
  test <- FixMakeModel("BMW","330I","^330.?I",test)
  test <- FixMakeModel("BMW","525I","^525.?I",test)
  test <- FixMakeModel("BMW","328I","^328.?I",test)
  test <- FixMakeModel("BMW","318","^318",test)
  test <- FixMakeModel("BMW","MINI","^MINI",test)
  test <- FixMakeModel("BMW","116I","^116.?I",test)
  test <- FixMakeModel("BMW","318TI","^318.?TI",test)
  test <- FixMakeModel("BMW","325I","^325.?I",test)
  test <- FixMakeModel("BMW","323","^323",test)
  test <- FixMakeModel("BMW","X5","^X5",test)
  test <- FixMakeModel("BMW","318I","^318.?I",test)
  test <- FixMakeModel("BMW","320I","^320.?I",test)
  
  test
}

FixKia <- function(test) {
  test <- FixMakeModel("KIA","K844","K844",test)
  test <- FixMakeModel("KIA","K844T","K844T",test)
  test <- FixMakeModel("KIA","K85","K85",test)
  test <- FixMakeModel("KIA","K85S","K85S",test)
  test <- FixMakeModel("KIA","K85SA","K85SA",test)
  test <- FixMakeModel("KIA","K85ST","K85ST",test)
  test <- FixMakeModel("KIA","K85STB","K85STB",test)
  test <- FixMakeModel("KIA","KC95","KC95",test)
  test <- FixMakeModel("KIA","KS4S","KS4S",test)
  test <- FixMakeModel("KIA","ROCSTA","ROCSTA",test)
  test <- FixMakeModel("KIA","SHUTTLESM","SHUTTLESM",test)
  test <- FixMakeModel("KIA","K64SA","K64SA",test)
  test <- FixMakeModel("KIA","K745A","K745A",test)
  test <- FixMakeModel("KIA","NIRO","NIRO",test)
  test <- FixMakeModel("KIA","CEED","CEED",test)
  test <- FixMakeModel("KIA","PRIDE","PRIDE",test)
  test <- FixMakeModel("KIA","SEDONA","SEDONA",test)
  test <- FixMakeModel("KIA","RONDO","RONDO",test)
  test <- FixMakeModel("KIA","CERES","CERES",test)
  test <- FixMakeModel("KIA","CREDOS","CREDOS",test)
  test <- FixMakeModel("KIA","SPECTRA","SPECTRA",test)
  test <- FixMakeModel("KIA","K2700","K2700",test)
  test <- FixMakeModel("KIA","K2900","K2900",test)
  test <- FixMakeModel("KIA","K2500","K2500",test)
  test <- FixMakeModel("KIA","CARENS","CARENS",test)
  test <- FixMakeModel("KIA","MENTOR","MENTOR",test)
  test <- FixMakeModel("KIA","KOUP","KOUP",test)
  test <- FixMakeModel("KIA","MAGENTIS","MAGENTIS",test)
  test <- FixMakeModel("KIA","SOUL","SOUL",test)
  test <- FixMakeModel("KIA","OPTIMA","OPTIMA",test)
  test <- FixMakeModel("KIA","PREGIO","PREGIO",test)
  test <- FixMakeModel("KIA","CARNIVAL","CARNIVAL",test)
  test <- FixMakeModel("KIA","PICANTO","PICANTO",test)
  test <- FixMakeModel("KIA","SORENTO","SORENTO",test)
  test <- FixMakeModel("KIA","CERATO","CERATO",test)
  test <- FixMakeModel("KIA","RIO","RIO",test)
  test <- FixMakeModel("KIA","SPORTAGE","SPORTAGE",test)

  test
}


FixAudi <- function(test) {
  test <- FixMakeModel("AUDI","A2","A2",test)
  test <- FixMakeModel("AUDI","100CD","100CD",test)
  test <- FixMakeModel("AUDI","TTS","TTS",test)
  test <- FixMakeModel("AUDI","CABRIOLET","CABRIOLET",test)
  test <- FixMakeModel("AUDI","SQ5","SQ5",test)
  test <- FixMakeModel("AUDI","S7","S7",test)
  test <- FixMakeModel("AUDI","90","90",test)
  test <- FixMakeModel("AUDI","RS7","^RS7",test)
  test <- FixMakeModel("AUDI","QUATTRO","QUATTRO",test)
  test <- FixMakeModel("AUDI","100","^100",test)
  test <- FixMakeModel("AUDI","R8","^R8",test)
  test <- FixMakeModel("AUDI","COUPE","^COUPE",test)
  test <- FixMakeModel("AUDI","RS5","^RS5",test)
  test <- FixMakeModel("AUDI","S8","^S8",test)
  test <- FixMakeModel("AUDI","80","^80",test)
  test <- FixMakeModel("AUDI","RS6","^RS6",test)
  test <- FixMakeModel("AUDI","S6","^S6",test)
  test <- FixMakeModel("AUDI","A7","^A7",test)
  test <- FixMakeModel("AUDI","A8","^A8",test)
  test <- FixMakeModel("AUDI","S5","^S5",test)
  test <- FixMakeModel("AUDI","RS4","^RS4",test)
  test <- FixMakeModel("AUDI","S3","^S3",test)
  test <- FixMakeModel("AUDI","A5","^A5",test)
  test <- FixMakeModel("AUDI","Q3","^Q3",test)
  test <- FixMakeModel("AUDI","S4","^S4",test)
  test <- FixMakeModel("AUDI","ALLROAD","^ALLROAD",test)
  test <- FixMakeModel("AUDI","A1","^A1",test)
  test <- FixMakeModel("AUDI","Q5","^Q5",test)
  test <- FixMakeModel("AUDI","TT","^TT",test)
  test <- FixMakeModel("AUDI","Q7","^Q7",test)
  test <- FixMakeModel("AUDI","A6","^A6",test)
  test <- FixMakeModel("AUDI","A3","^A3",test)
  test <- FixMakeModel("AUDI","A4","^A4",test)

  test
}

FixMercedes_benz <- function(test) {
  test <- FixMakeModel("MERCEDES-BENZ","230","230",test)
  test <- FixMakeModel("MERCEDES-BENZ","E280","E280",test)
  test <- FixMakeModel("MERCEDES-BENZ","VIANO","VIANO",test)
  test <- FixMakeModel("MERCEDES-BENZ","U1700L","U1700L",test)
  test <- FixMakeModel("MERCEDES-BENZ","S280","S280",test)
  test <- FixMakeModel("MERCEDES-BENZ","ML320","ML320",test)
  test <- FixMakeModel("MERCEDES-BENZ","ATEGO","ATEGO",test)
  test <- FixMakeModel("MERCEDES-BENZ","A190","A190",test)
  test <- FixMakeModel("MERCEDES-BENZ","B-CLASS","B-CLASS",test)
  test <- FixMakeModel("MERCEDES-BENZ","GLE-CLASS","GLE-CLASS",test)
  test <- FixMakeModel("MERCEDES-BENZ","320","320",test)
  test <- FixMakeModel("MERCEDES-BENZ","500","500",test)
  test <- FixMakeModel("MERCEDES-BENZ","GLC-CLASS","GLC-CLASS",test)
  test <- FixMakeModel("MERCEDES-BENZ","C230","C230",test)
  test <- FixMakeModel("MERCEDES-BENZ","E200","E200",test)
  test <- FixMakeModel("MERCEDES-BENZ","B170","B170",test)
  test <- FixMakeModel("MERCEDES-BENZ","E500","E500",test)
  test <- FixMakeModel("MERCEDES-BENZ","C250","C250",test)
  test <- FixMakeModel("MERCEDES-BENZ","C280","C280",test)
  test <- FixMakeModel("MERCEDES-BENZ","M-CLASS","M-CLASS",test)
  test <- FixMakeModel("MERCEDES-BENZ","SLK230","SLK230",test)
  test <- FixMakeModel("MERCEDES-BENZ","ML350","ML350",test)
  test <- FixMakeModel("MERCEDES-BENZ","B200","B200",test)
  test <- FixMakeModel("MERCEDES-BENZ","A-CLASS","A-CLASS",test)
  test <- FixMakeModel("MERCEDES-BENZ","CLS","CLS",test)
  test <- FixMakeModel("MERCEDES-BENZ","E320","E320",test)
  test <- FixMakeModel("MERCEDES-BENZ","A170","A170",test)
  test <- FixMakeModel("MERCEDES-BENZ","CLA-CLASS","CLA-CLASS",test)
  test <- FixMakeModel("MERCEDES-BENZ","GLA-CLASS","GLA-CLASS",test)
  test <- FixMakeModel("MERCEDES-BENZ","C240","C240",test)
  test <- FixMakeModel("MERCEDES-BENZ","E350","E350",test)
  test <- FixMakeModel("MERCEDES-BENZ","ACTROS","ACTROS",test)
  test <- FixMakeModel("MERCEDES-BENZ","190E","190E",test)
  test <- FixMakeModel("MERCEDES-BENZ","SLK","SLK",test)
  test <- FixMakeModel("MERCEDES-BENZ","VITO","VITO",test)
  test <- FixMakeModel("MERCEDES-BENZ","C180","C180",test)
  test <- FixMakeModel("MERCEDES-BENZ","CLK","CLK",test)
  test <- FixMakeModel("MERCEDES-BENZ","A160","A160",test)
  test <- FixMakeModel("MERCEDES-BENZ","C-CLASS","C-CLASS",test)
  test <- FixMakeModel("MERCEDES-BENZ","C20","C20",test)
  test <- FixMakeModel("MERCEDES-BENZ","SPRINTER","SPRINTER",test)

  test
}








