
  fleet <- FixMakes(fleet)
  fleet <- FixToyota(fleet)
  fleet <- FixAstonMartin(fleet)
  fleet <- FixNissan(fleet)
  fleet <- FixHonda(fleet)
  fleet <- FixFord(fleet)
  fleet <- FixHolden(fleet)
  fleet <- FixMazda(fleet)
  fleet <- FixMitsubishi(fleet)
  fleet <- FixSuzuki(fleet)
  fleet <- FixSubaru(fleet)
  fleet <- FixVolkswagen(fleet)
  fleet <- FixHyundai(fleet)
  fleet <- FixBmw(fleet)
  fleet <- FixKia(fleet)
  fleet <- FixAudi(fleet)
  fleet <- FixMercedes_benz(fleet)

